# Generated by Django 5.2.9 on 2026-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
