# Generated by Django 5.2.9 on 2026-04-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_category_country_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='country.category'),
            preserve_default=False,
        ),
    ]
