# Generated by Django 5.2.9 on 2026-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_alter_cat_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='countries', to='country.tagpost'),
        ),
    ]
