# Generated by Django 5.2.9 on 2026-04-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_tagpost_country_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='extrainfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_extrainfo', to='country.extrainfo'),
        ),
    ]
